---
title: "Codeforces: Problem 1758D"
tags: ["codeforces", "number-theory"]
publish-date: "March 9, 2024"
description: |
  A nice 1800 rated Codeforces problem on constructing an integer sequence. Multiple attempts, because an initial strategy doesn't always work but is nice to document.
