---
title: "Project Euler: Problem 743"
tags: ["project-euler", "combinatorics", "matrices"]
publish-date: "June 25, 2024"
description: |
  Solving Project Euler Problem 743, a really nice combo problem using a sliding window approach.
