---
title: "Music-Inspired Mathematics"
tags: ["fourier-transform", "signal-processing", "analysis", "linear-algebra"]
publish-date: "March 21, 2025"
description: |
  An orchestra assignment special! In this article, I explore the connection
  between music and math concretely. In particular, we'll take a look at some
  signal processing and some even more out there connections to springboard
  into some fun pure math.
wip: false
