---
title: "An Electromagnetism Cycloid"
tags: ["mini", "physics", "linear-algebra", "differential-equations", "complex-numbers"]
publish-date: "April 1, 2025"
description: |
  Not an April Fool's joke! This is a mini article on an electromagnetism problem mentioned in one of our class's textbooks. The exact solution was said to be beyond the scope of the textbook, so, don't mind if I do!
wip: false
