---
title: "Codeforces: Problem 1902C"
tags: ["codeforces", "number-theory", "optimization"]
publish-date: "March 24, 2024"
description: |
  A quick little number theory Codeforces problem on minimizing costs.
