---
title: "Codeforces: Problem 1916H1"
tags: ["codeforces", "linear-algebra", "matrices", "combinatorics", "number-theory"]
publish-date: "July 21, 2024"
description: |
  A very mathy and beautiful 2700 rated Codeforces problem. This one had me really excited to solve.
