---
title: "A Combinatorial Totient Sum Identity"
tags: ["mini", "combinatorics", "number-theory"]
publish-date: "December 21, 2024"
description: |
  A very small article before winter break, featuring a clean double counting argument for a sum involving the Euler totient function.
wip: false
