---
title: "Codeforces: Problem 1948E"
tags: ["codeforces", "graph-theory", "number-theory", "permutations"]
publish-date: "March 15, 2024"
description: |
  A fun (slightly brute-force) constructive graph theory Codeforces problem, rated 2100.
