---
title: "Project Euler: Problem 421"
tags: ["project-euler", "number-theory", "group-theory", "probability", "combinatorics", "cryptography"]
publish-date: "August 2, 2024"
description: |
  Solving Project Euler Problem 421, a beautiful number theory puzzle on counting roots modulo primes with a cryptographic and probabilistic flavor.
