---
title: "Proving that the Euler Totient is Even"
tags: ["number-theory", "group-theory"]
publish-date: "July 23, 2024"
description: |
  We prove that the Euler totient function is even using group theory.
