---
title: "Yukicoder: Problem 2664"
tags: ["yukicoder", "graph-theory", "dfs", "number-theory"]
publish-date: "April 1, 2024"
description: |
  Solving Yukicoder Problem 2664, a quick little graph and number theory problem, with the extra challenge of having to read the problem description in Japanese.
