---
title: "Codeforces: Problem 1763D"
tags: ["codeforces", "combinatorics", "permutations"]
publish-date: "July 5, 2024"
description: |
  A 2200 rated Codeforces combinatorics problem with a whole lot of casework.
