---
title: "Project Euler: Problem 752"
tags: ["project-euler", "number-theory", "matrices", "abstract-algebra", "group-theory"]
publish-date: "December 5, 2024"
description: |
  Solving Project Euler Problem 752, a nice problem on orders in fields with square roots.
wip: false
