---
title: "Project Euler: Problem 549"
tags: ["project-euler", "number-theory"]
publish-date: "June 7, 2024"
description: |
  Solving Project Euler Problem 549, a nice number theory problem revolving around the factorization of factorials.
