---
title: "Binomial Coefficient Matrices"
tags: ["linear-algebra", "matrices", "combinatorics", "binomial-coefficient"]
publish-date: "June 30, 2024"
description: |
  Let's explore the properties of lower triangular matrices filled with binomial coefficients.
