---
title: "Project Euler: Problem 779"
tags: ["project-euler", "number-theory", "analysis", "primes"]
publish-date: "June 23, 2024"
description: |
  Solving Project Euler Problem 779, a really beautiful number theory problem.
