---
title: "PUMAC Power Round 2024: The Hausdorff Measure"
tags: ["notes", "contest", "topology", "measure-theory"]
publish-date: "November 28, 2024"
description: |
  Notes on and a review of what our team managed to solve in PUMAC Power Round 2024! Featuring measure theory, topology, and fractals.
wip: false
