---
title: "Codeforces: Problem 1909D"
tags: ["codeforces", "number-theory", "optimization"]
publish-date: "April 7, 2024"
description: |
  A nice little 1900 rated Codeforces problem on making all elements equal with operations.
